version: 2.1

# the default pipeline parameters, which will be updated according to
# the results of the path-filtering orb
parameters:
  run-build-grc-stamp:
    type: boolean
    default: false
  run-build-grc-stamp-frontend:
    type: boolean
    default: false

defaults: &defaults
  working_directory: ~/app
  docker:
    - image: cimg/node:20.12.2

jobs:
  lint_commit_message:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }} # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: npm ci
      - save_cache:
          paths:
            - ~/app/node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Define environment variable with lastest commit's message
          command: |
            cd ~/app
            echo 'export COMMIT_MESSAGE=$(git log -1 --pretty=format:"%s")' >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Lint commit message
          command: echo "$COMMIT_MESSAGE" | npx commitlint

  grc-stamp_build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "packages/grc-stamp/package.json" }} # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: cd ~/app/packages/grc-stamp && npm ci
      - run: cd ~/app/packages/grc-stamp && npm run build
      - save_cache:
          paths:
            - ~/app/packages/grc-stamp/node_modules
          key: v1-dependencies-{{ checksum "packages/grc-stamp/package.json" }}
      - persist_to_workspace:
          root: ~/app
          paths: .

  grc-stamp_run_typecheck:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/app
      - run:
          name: Run typechecks
          command: cd ~/app/packages/grc-stamp && npm run typecheck

  grc-stamp_test-integration:
    <<: *defaults
    docker:
      - image: cimg/node:20.12.2
      - image: cimg/mysql:5.7
        environment:
          MYSQL_RANDOM_ROOT_PASSWORD: true
          MYSQL_USER: test
          MYSQL_PASSWORD: test
          MYSQL_DATABASE: test
    steps:
      - attach_workspace:
          at: ~/app
      - run:
          name: Wait for mysql
          command: sleep 7
      - run:
          name: Run integration tests
          command: cd ~/app/packages/grc-stamp && npm run test:integration

  grc-stamp_test-unit:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/app
      - run:
          name: Run unit tests
          command: cd ~/app/packages/grc-stamp && npm run test:unit

  grc-stamp_test-lint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/app
      - run:
          name: Run lint tests
          command: cd ~/app/packages/grc-stamp && npm run test:lint

  grc-stamp_release:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/app
      - run:
          name: Trust this ssh key
          command: mkdir -p ~/.ssh/ && touch ~/.ssh/known_hosts && ssh-keyscan github.com >> ~/.ssh/known_hosts
      - run:
          name: Semantic release
          command: cd ~/app/packages/grc-stamp && npm run semantic-release

  grc-stamp-frontend_checkout_code:
    <<: *defaults
    steps:
      - checkout
      - persist_to_workspace:
          root: ~/app
          paths:
            - .

  grc-stamp-frontend_bundle:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/app
      - restore_cache:
          key: npm-v1-{{ checksum "packages/grc-stamp-frontend/package-lock.json" }}
      - run: cd ~/app/packages/grc-stamp-frontend && npm ci
      - save_cache:
          key: npm-v1-{{ checksum "packages/grc-stamp-frontend/package-lock.json" }}
          paths:
            - ~/app/packages/grc-stamp-frontend/node_modules
      - persist_to_workspace:
          root: ~/app
          paths: .

  grc-stamp-frontend_run_test:
    <<: *defaults
    parallelism: 4
    steps:
      - attach_workspace:
          at: ~/app
      - run:
          name: run tests
          command: cd ~/app/packages/grc-stamp-frontend && npm run test


  grc-stamp-frontend_run_lint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/app
      - run:
          name: Run JS Linter
          command: cd ~/app/packages/grc-stamp-frontend && npm run lint

  grc-stamp-frontend_run_typecheck:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/app
      - run:
          name: Run typechecks
          command: cd ~/app/packages/grc-stamp-frontend && npm run typecheck

  grc-stamp-frontend_release:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/app
      - run:
          name: Trust this ssh key
          command: mkdir -p ~/.ssh/ && touch ~/.ssh/known_hosts && ssh-keyscan github.com >> ~/.ssh/known_hosts
      - run:
          name: Semantic release
          command: cd ~/app/packages/grc-stamp-frontend && npm run semantic-release



workflows:
  grc-stamp_build-and-deploy:
    when: << pipeline.parameters.run-build-grc-stamp >>
    jobs:
      - grc-stamp_build

      - grc-stamp_run_typecheck:
          requires:
            - grc-stamp_build

      - grc-stamp_test-integration:
          requires:
            - grc-stamp_build

      - grc-stamp_test-unit:
          requires:
            - grc-stamp_build

      - grc-stamp_test-lint:
          requires:
            - grc-stamp_build

      - grc-stamp_release:
          filters:
            branches:
              only: master
          requires:
            - grc-stamp_build
            - grc-stamp_run_typecheck
            - grc-stamp_test-integration
            - grc-stamp_test-unit
            - grc-stamp_test-lint

  grc-stamp-frontend_build-and-deploy:
    when: << pipeline.parameters.run-build-grc-stamp-frontend >>
    jobs:
      - grc-stamp-frontend_checkout_code

      - grc-stamp-frontend_bundle:
          requires:
            - grc-stamp-frontend_checkout_code

      - grc-stamp-frontend_run_lint:
          requires:
            - grc-stamp-frontend_bundle

      - grc-stamp-frontend_run_typecheck:
          requires:
            - grc-stamp-frontend_bundle

      - grc-stamp-frontend_run_test:
          requires:
            - grc-stamp-frontend_bundle

      - grc-stamp-frontend_release:
          filters:
            branches:
              only: master
          requires:
            - grc-stamp-frontend_run_test
            - grc-stamp-frontend_run_typecheck
            - grc-stamp-frontend_run_lint


