version: 2.1

# the default pipeline parameters, which will be updated according to
# the results of the path-filtering orb
parameters:
  run-build-grc-stamp:
    type: boolean
    default: false
  run-build-grc-stamp-frontend:
    type: boolean
    default: false

defaults: &defaults
  working_directory: ~/app
  docker:
    - image: cimg/node:22.16

jobs:
  grc-stamp-frontend_checkout_code:
    <<: *defaults
    steps:
      - checkout
      - persist_to_workspace:
          root: ~/app
          paths:
            - .

  grc-stamp-frontend_bundle:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/app
      - restore_cache:
          key: npm-v1-{{ checksum "packages/grc-stamp-frontend/package-lock.json" }}
      - run: cd ~/app/packages/grc-stamp-frontend && npm ci
      - save_cache:
          key: npm-v1-{{ checksum "packages/grc-stamp-frontend/package-lock.json" }}
          paths:
            - ~/app/packages/grc-stamp-frontend/node_modules
      - persist_to_workspace:
          root: ~/app
          paths: .

  grc-stamp-frontend_run_test:
    <<: *defaults
    parallelism: 4
    steps:
      - attach_workspace:
          at: ~/app
      - run:
          name: run tests
          command: cd ~/app/packages/grc-stamp-frontend && npm run test


  grc-stamp-frontend_run_lint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/app
      - run:
          name: Run JS Linter
          command: cd ~/app/packages/grc-stamp-frontend && npm run lint

  grc-stamp-frontend_run_typecheck:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/app
      - run:
          name: Run typechecks
          command: cd ~/app/packages/grc-stamp-frontend && npm run typecheck

  grc-stamp-frontend_release:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/app
      - run:
          name: Trust this ssh key
          command: mkdir -p ~/.ssh/ && touch ~/.ssh/known_hosts && ssh-keyscan github.com >> ~/.ssh/known_hosts
      - run:
          name: Semantic release
          command: cd ~/app/packages/grc-stamp-frontend && npm run semantic-release



workflows:
  grc-stamp-frontend_build-and-deploy:
    when: << pipeline.parameters.run-build-grc-stamp-frontend >>
    jobs:
      - grc-stamp-frontend_checkout_code

      - grc-stamp-frontend_bundle:
          requires:
            - grc-stamp-frontend_checkout_code

      - grc-stamp-frontend_run_lint:
          requires:
            - grc-stamp-frontend_bundle

      - grc-stamp-frontend_run_typecheck:
          requires:
            - grc-stamp-frontend_bundle

      - grc-stamp-frontend_run_test:
          requires:
            - grc-stamp-frontend_bundle

      - grc-stamp-frontend_release:
          filters:
            branches:
              only: master
          requires:
            - grc-stamp-frontend_run_test
            - grc-stamp-frontend_run_typecheck
            - grc-stamp-frontend_run_lint


